### ISSUE TITLE
Message: 'phantomjs' executable needs to be in PATH. 

### ISSUE THREAD

**Issue by AndriasP** [austinjhunt/msci_esg#2]
Trying to use this package for scraping from MSCI, but I can't seem to get it working. 
I get this error:
"Message: 'phantomjs' executable needs to be in PATH. "
I tried downloading some driver for phantomJs and using webdriver, which I imagine is included in your package.
Any tips or fixes?

**Comment by austinjhunt** [comment]
Hi @AndriasP 

I'm sorry for the delay getting back to you. Here is how to solve this problem, if you have not already: 

1) Download PhantomJS from this link: https://phantomjs.org/download.html
2) Once you download it, place it in the directory where you want it to stay. For my case, I'll place it in my Applications folder (I'm running MacOS): `/Applications/<here>`
3) Once you've placed it somewhere, add the path to the "bin" folder within phantomjs to your PATH environment variable. Since I placed the phantomjs downloaded folder into /Applications, I run:
`export PATH=$PATH:/Applications/phantomjs-2.1.1-macosx/bin/`
Now, when I execute the ratefinder script, I get: 
`{'rating-paragraph': 'Tesla is average among 40 companies in the automobiles industry.', 'rating-history-paragraph': "Tesla's rating remains unchanged since April, 2019.", 'current': {'esg_rating': 'a', 'esg_category': 'average'}, 'history': {'jul-17': '', 'apr-18': '', 'aug-18': '', 'apr-19': '', 'apr-20': ''}}`
